### ISSUE TITLE
Multiple wallpapers/slideshow

### ISSUE THREAD

**Issue by Smumbo** [Yanndroid/DualWallpaper#10]
This is a pretty big request, so no worries if you decide not to pursue, but I think it would be amazing if you could add slideshow functionality.

Instead of one wallpaper for each theme, this would let users select multiple wallpapers, and the app would automatically change the wallpaper to a different random wallpaper after whatever length of time the user sets.

**Comment by Yanndroid** [comment]
It's definitely possible, but it doesn't really fit the app's purpose. If at all, this should be a new separate app and I have even less time for that.
Sorry.

**Comment by Smumbo** [comment]
Totally understandable.
