### ISSUE TITLE
Feature request: Multiple Wallpapers

### ISSUE THREAD

**Issue by GalacticSenat** [Yanndroid/DualWallpaper#12]
Would it be possible to select multiple Wallpapers for Start/Lock-Screen?

For example: I have 3 Wallpapers set for my Lockscreen that rotate each time i open the phone, but if I use the app i am restricted to only one.

**Comment by Yanndroid** [comment]
DualWallpaper (or any other third party app) can't detect when the phone is opened and you can't give the system multiple wallpapers to choose from. Samsung integrated their Wallpaper Services in the system.

But you can just choose no wallpaper in DualWallpaper for the lockscreen (both light and dark) and then use Samsung's Wallpaper Servies.
