### ISSUE TITLE
"Your current wallpaper is not supported" Toast message

### ISSUE THREAD

**Issue by ChaliceChore** [Yanndroid/DualWallpaper#20]
When I choose **Use current** on the **Dark** tab a toast error is displayed "Your current wallpaper is not supported".
I use the [Backdrops](https://play.google.com/store/apps/details?id=com.backdrops.wallpapers) app to change my wallpper.
I have realme GT 2 Pro (reame UI 5).
I need to download wallpaper from Backdrops and choose the image from Dual Wallpaper app to set the wallpaper.

Please fix this issue.

**Comment by Yanndroid** [comment]
Only in the Dark tab? This seems strange.
If you're on Android 13 or 14 this shouldn't work at all anyway,  because Google changed file permissions and forgot that requesting the wallpaper needs it.

**Comment by ChaliceChore** [comment]
> Only in the Dark tab? This seems strange.

My mistake. It happens on both tabs.





> If you're on Android 13 or 14 this shouldn't work at all anyway, because Google changed file permissions and forgot that requesting the wallpaper needs it.

Yeah, I'm on Android 14. Is there a potential fix for this? Or, will it stay this way unless Google changes things?

**Comment by Yanndroid** [comment]
Unfortunately, there's nothing I or Google can do about it. They can't change already-released Android versions, so it might work in Android 15 again, but not 13 and 14. And even this, I think they don't really give a f.
They only way currently, would be to request full file permissions, but then Play Store policies would get in the way.
Sorry.
