### ISSUE TITLE
Switch wallpaper based on time

### ISSUE THREAD

**Issue by JVariance** [Yanndroid/DualWallpaper#3]
I currently use https://github.com/cvzi/darkmodewallpaper, which has this functionality, but your app looks way better (especially considering that I use a Galaxy phone), so I'd like to see this feature in DualWallpaper 😃

Since I always have the night mode enabled, DualWallpaper doesn't fit my needs as of now.

**Comment by Yanndroid** [comment]
This feature wasn't part of my plans but I guess it does make sense when you always have dark mode enabled, so I think I'll add it. Same goes for #4, but I'm really busy with other projects lately so it might take some time.

**Comment by Yanndroid** [comment]
Added in 3a3d4dec6e8b7be729ea6b53f99d13acd18971ff and released with [v2.0.0](/Yanndroid/DualWallpaper/releases/tag/v2.0.0).
