### ISSUE TITLE
SystemUI keeps hanging

### ISSUE THREAD

**Issue by ciriousjoker** [Yanndroid/DualWallpaper#7]
Whenever the wallpaper switches, the SystemUI process freezes and I get the ANR dialog.

Have a Pixel 4XL. I feel like lately my device has gotten slower, but apart from that stability is usually great.

I haven't rebooted my device so far though, will report back (and potentially close this) once I did that.

Wanted to create the issue anyway in case someone else faces the same issue and to say thanks for the otherwise great app :)

**Comment by ciriousjoker** [comment]
Nope, still crashing, sadly can't use this. Seems like changing the wallpaper takes so long that Android thinks SystemUI is dead...

**Comment by Yanndroid** [comment]
This is strange, I can't imagine why SystemUI would be crashing... which mode are you using currently?

And for the performance issues; does your device feel slower since you've installed the app? If yes, is it also slow when you turn the service off or just when it on?

**Comment by ciriousjoker** [comment]
My bad, I shouldn't have said "crashing". It just freezes completely for ~6 seconds and because of that I get the ANR dialog.

I'm using the service mode and the notification is visible.

Performance: My device feels a bit slower than it used to, but that has nothing to do with this app. With this app, performance is unchanged up to the point where the wallpaper changes. At that point everything freezes.

**Comment by Yanndroid** [comment]
Were the images you used of a high resolution? If that is the case, your issue maybe got fixed with 3a3d4dec6e8b7be729ea6b53f99d13acd18971ff.
(Release: [v2.0.0](/Yanndroid/DualWallpaper/releases/tag/v2.0.0))

**Comment by ciriousjoker** [comment]
Yes, they were, I'll give this another try :)

**Comment by ciriousjoker** [comment]
@Yanndroid Can't reproduce this anymore, seems to have worked perfectly. Thanks for the great work!
