### ISSUE TITLE
App keep changing color and freeze

### ISSUE THREAD

**Issue by NeverSm1le** [Yanndroid/DualWallpaper#9]
This bug seems to affect newer 2.x version only. The apps keep changing the color then freeze for a short time if lockscreen/primary wallpaper is 2 different one, makes it impossible to do anything unless the switch is turned off or do it fast.

**Comment by Yanndroid** [comment]
Hi there, thanks for reporting this issue. Could you maybe provide more information about it?
- device and android version
- mode (theme or time)
- are you using images, a plain color or a gradient

And what do you mean with the apps keep changing the color?

**Comment by NeverSm1le** [comment]
Here's it in action: https://imgur.com/a/8OqBpME. Turn out not just the app but it change the color palette of the whole system as well.

**Comment by Yanndroid** [comment]
I think I know what was happening. Could you try out this version with theme trigger?
[app-debug.zip](https://github.com/Yanndroid/DualWallpaper/files/11286420/app-debug.zip)  (rename the file to .apk)

**Comment by NeverSm1le** [comment]
> I think I know what was happening. Could you try out this version with theme trigger? [app-debug.zip](https://github.com/Yanndroid/DualWallpaper/files/11286420/app-debug.zip) (rename the file to .apk)

Sorry for the ultra late reply (got lost in the middle of changing PC, the new apk no longer changing color then freeze (as expected in v1)
